language: java
jdk:
 - oraclejdk8
before_install:
 - chmod +x mvnw
after_install:
 - mv target/pha-1.0.war target/ROOT.war
env:
  global:
    - "FTP_USER=pha5620\meerkat"
    - "FTP_PASSWORD=Elec5620"
after_success:
    "curl --ftp-create-dirs -T target/ROOT.war -u $FTP_USER:$FTP_PASSWORD ftp://waws-prod-sn1-131.ftp.azurewebsites.windows.net/site/wwwroot/webapps"
    
#deploy:
#  provider: azure_web_apps
#  username: pha5620\meerkat       # If AZURE_WA_USERNAME isn't set
#  password: Elec5620   # If AZURE_WA_PASSWORD isn't set
#  site: pha5620       # If AZURE_WA_SITE isn't set
#  slot:       # (optional) If AZURE_WA_SLOT isn't set
