language: java
jdk:
 - oraclejdk8
before_install:
 - chmod +x mvnw
env:
  global:
    - "FTP_USER=pha5620\\meerkat"
    - "FTP_PASSWORD=Elec5620"
after_success:
 - mv target/pha-1.0.war target/ROOT.war
 - curl -T target/ROOT.war -u pha5620\\meerkat:Elec5620 ftp://waws-prod-sn1-131.ftp.azurewebsites.windows.net/site/wwwroot/webapps/
    
#deploy:
#  provider: azure_web_apps
#  username: pha5620\meerkat       # If AZURE_WA_USERNAME isn't set
#  password: Elec5620   # If AZURE_WA_PASSWORD isn't set
#  site: pha5620       # If AZURE_WA_SITE isn't set
#  slot:       # (optional) If AZURE_WA_SLOT isn't set
